services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - mysql
            - caddy

    node:
        image: node:20
        container_name: laravel_node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: [ "npm", "run", "docker-dev" ]
        ports:
            - "5173:5173"
        networks:
            - laravel_network
        profiles:
            - frontend

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

    caddy:
        image: caddy:latest
        container_name: laravel_caddy
        volumes:
            - .:/var/www/html
            - ./Caddyfile:/etc/caddy/Caddyfile
        ports:
            - "80:80"
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    mysql_data:
